name: Publish Package
run-name: ${{ github.actor }} is publishing NPM package to registry 🚀
on: [push]

env:
  NODE_VERSION: 18  # Define the Node.js version as a workflow-level environment variable

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:$NODE_VERSION
    steps:
    - run: echo "Node version:" $NODE_VERSOPM
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: $NODE_VERSION

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test